### PR TITLE
Update Misc.md

### PR DESCRIPTION
**Pull request by itpupkin**
Added a new section of alternative frontends. Expanded information available.

### CODE REVIEW

**Comment by kekkodance** [comment]
Upstream your fork.

**Comment by kekkodance** [comment]
Most of the tools you include here are redundant/useless. the only remotely useful stuff is:

Minimal Youtube
Google Unlocked
OpenSourceAlternativeTo

imgburn is linked to installing malware if you're not careful, along with being a tool overshadowed by balenaetcher and ventoy.

the "random noise generator" doesn't increase your privacy and never will, it just causes more confusion for the users.

The list of alternative frontends is not something we're willing to maintain as there seems to be a constant fight between Corporations and FOSS authors. A link which has a maintained list would be much preferred.

Spytify is a subpar tool and you put it in the wrong section.

**Comment by kekkodance** [comment]
Waiting on @Helmasko for merge.

**Comment by Helmasko** [comment]
I decided to remove minimal youtube since I dont think its something that our guide aims to have

**Comment by Helmasko** [comment]
It's been 3 days without a response, so I will merge this fork now. Thanks for your contribution.

**Pull request merged**
