### PR TITLE
Update Music.md

### PR DESCRIPTION
**Pull request by Myuui**
replaced dyvolt by their official discord server

### CODE REVIEW

**Comment by kekkodance** [comment]
i'm sorry but, this seems like a downgrade??

**Comment by Helmasko** [comment]
slavarts discord gets replaced on a weekly basis, no one wants to update it that often. instead ppl can go on divolt and get the updated discord link

**Comment by Myuui** [comment]
> slavarts discord gets replaced on a weekly basis, no one wants to update it that often. instead ppl can go on divolt and get the updated discord link

Server has been on for more than a month, and I would take care to update the link.

**Comment by kekkodance** [comment]
i think the majority of people here want PRs to be about adding things or making the guide better, not the "monthly slavart update" commit. also, we're not going to rely on someone we don't know to tell us when to change out a link.

**Pull request closed without merging**
