### PR TITLE
More OS listings for Dolphin as a Wii emulator

### PR DESCRIPTION
**Pull request by 5h3i1ah**
Added Mac, Linux, and Android listings for Dolphin as a Wii emulator

### CODE REVIEW

**Comment by kekkodance** [comment]
the uptodown link, no.

**Comment by kekkodance** [comment]
put the proper source for the dolphin app for android and i will merge

**Comment by 5h3i1ah** [comment]
done! and updated the same link for Gamecube

**Comment by Helmasko** [comment]
I dont see any android download links on https://dolphin-emu.org/, is it actually on there? The only official place i know is https://play.google.com/store/apps/details?id=org.dolphinemu.dolphinemu

**Pull request merged**
