### PR TITLE
Add Googleplay store direct downloader

### PR DESCRIPTION
**Pull request by Jorc0**

### CODE REVIEW

**Comment by kekkodance** [comment]
fix missing capitals on some words and also wording, for the love of god, add names to what the PRs do

**Comment by Jorc0** [comment]
I hope its that what you meant @kekkodance also, sorry, but what's "PRs"?

**Comment by WadieBenabdouh** [comment]
Great addition

**Comment by Helmasko** [comment]
Thanks for the contribution! @Jorc0 but next time try to remember to add a proper title to your pull requests/issues.

**Comment by Jorc0** [comment]
> Thanks for the contribution! @Jorc0 but next time try to remember to add a proper title to your pull requests/issues.

Yessir thanks 👍🏻

**Pull request merged**
