### PR TITLE
Killshot1337x patch 1

### PR DESCRIPTION
**Pull request by Killshot1337x**

### CODE REVIEW

**Comment by Killshot1337x** [comment]
Added an ebooks section

**Comment by Helmasko** [comment]
ok i will be merging this and will continue to edit it later. thanks for the contribution.

**Comment by Helmasko** [comment]
lol forgot to merge

**Comment by Killshot1337x** [comment]
image
### Small bug, the site has 2 audio book sections now.

**Comment by Helmasko** [comment]
Im still working on it slowly, it might take some time before ive completely gone through it

**Comment by Helmasko** [comment]
Also if there are any sites that you'd like to mention that don't have much content, you can and I'll remove them.

**Pull request merged**
