### PR TITLE
These are commits on the mobile section that I think are neccessary.

### PR DESCRIPTION
**Pull request by ughmaires**
- Added more things to iOS section, including jailbreaking and fixed formatting
- Added Mobilism to android section and fixed formatting and notes.

### CODE REVIEW

**Comment by kekkodance** [comment]
why did you delete the two spaces in commit b67644f ?

**Comment by ughmaires** [comment]
they weren't needed since i fixed the formatting


before
before

after
after

**Comment by kekkodance** [comment]
discord username?

**Comment by ughmaires** [comment]
Maires#4978

**Pull request merged**
