### PR TITLE
Added Rezi.one

### PR DESCRIPTION
**Pull request by Wamy-Dev**
put under Other section. might need some content changes....

### CODE REVIEW

**Comment by kekkodance** [comment]
No.

**Comment by Wamy-Dev** [comment]
Could you explain why rather than just saying "no." and giving no reason?

**Comment by kekkodance** [comment]
Ripped does not stoop as low and as unethical as your site. We choose to not include tools like this which link to unsafe and low quality sites in order to keep the guide's quality and trustworthiness. Please do not state points you have already stated in the issue i made on your repo, otherwise this PR will be locked.

**Comment by Wamy-Dev** [comment]
Other than SteamRipped (which I may remove if given the possibility to be added to this megathread) could you please share what sites are deemed untrustworthy so I may remove them?

**Comment by kekkodance** [comment]
None. Your tool won't be added. If a site isn't on our trusted list, it's not reviewed by us and possibly malicious or low quality.
We'd much rather self-host our own version BUT, this is an unethical tool and we recommend for users to not be spoonfed and instead, experience the intended way that a site is meant to be seen.

**Comment by Wamy-Dev** [comment]
lmao, suite yourself

**Comment by kekkodance** [comment]
Unfortunately, due to being a "megathread" with higher standards and a slight level of professionalism (unlike some others), this also means our review process for resources is much stricter. We're sorry your source didn't meet our standards and this decision is **permanent**.

**Pull request closed without merging**
