### PR TITLE
Add comics section

### PR DESCRIPTION
**Pull request by mayonaise60**
Updated manga.md to include a comic section.

### CODE REVIEW

**Review by Helmasko — COMMENTED** [review]
noice

**Comment by kekkodance** [comment]
Please merge this PR or integrate it with the existing section. @Helmasko

**Comment by Helmasko** [comment]
> Please merge this PR or integrate it with the existing section. @Helmasko

Waiting for @mayonaise60 since I'll be working with him.

**Comment by abUwUser** [comment]
~~is this thread alive?~~

**Comment by kekkodance** [comment]
> ~is this thread alive?~

if you wish to help out

**Pull request closed without merging**
